### ISSUE TITLE
128 bar code should end at 2331112

### ISSUE THREAD

**Issue by wsrtd** [victorheid/arduino_barcode128#1]
This library is very good. But I can't scan it with my mobile phone using the barcode generated by it. So I looked up a lot of information and found that the end of the bar code was one less.

         // Input -> 11648
        // Output -> "211412123221123221223112221231311222132212233111"
output should be  "2114121232211232212231122212313112221322122331112"。

 String bars = barcode.make(text);

The bars array should end up with a "2".

**Comment by victorheid** [comment]
I've fixed the ending sequence to use a different sequence pattern - You can check it on Barcode.cpp:166

I'm not sure if that is result of some different implementation used by the scanners, as the generated patter was read by my phone.
